services:

  traefik:
    image: traefik:v2.10

  mysql:
    image: mysql:8.2

  php:
    build:
      context: .
      target: base
    depends_on:
      - traefik
      - mysql

  redis:
     image: redis:7.2
